server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001


swagger:
  resourcePackage: com.github.engfragui.graphql.mockapis.routes
  schemes:
    - http



# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    com.github.engfragui.graphql.mockapis: ALL

  appenders:
    - type: console
